[package]
name = "minecraft-compose"
version = "0.1.0"
authors = ["Dave Korhumel <dpk2442@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
toml = "0.5.8"
serde = { version = "1.0.127", features = ["derive"] }
